### ISSUE TITLE
Migrate to USWDS 3.0?

### ISSUE THREAD

**Issue by lpsinger** [bruffridge/nasawds#12]
In our project (https://gcn.nasa.gov), source at https://github.com/nasa-gcn/gcn.nasa.gov) we use nasawds with [@trussworks/react-uswds](https://github.com/trussworks/react-uswds), which now depends on USWDS 3.0. We would like to see nasawds migrate to USWDS 3.0 as well. Is this already something that you plan to do?

**Comment by bruffridge** [comment]
Thanks for bringing this to my attention. I will look into migrating NASAWDS to USWDS 3.0.
